site_name: pyFlies

site_description: A Domain-Specific Language (DSL) for specification of experiments in cognitive cognitive sciences
site_author: Igor DejanoviÄ‡

repo_url: https://github.com/pyflies/pyflies
theme: readthedocs
extra_css: [style.css, css/version-select.css]

pages:
- Home: index.md
- Getting started: getting_started.md
- Test definition: test.md
- Condition tables: condition-tables.md
- Timing specification: timing.md
- Components: components.md
- About:
    - Release Notes: about/release_notes.md
    - Contributing: about/contributing.md
    - License: about/license.md

markdown_extensions:
    - admonition:

